### ISSUE TITLE
roachprod wipe local fails 

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/roachprod#100]
`roachprod create local`, `roachprod start local` all worked fine. After that I attempted a wipe, which resulted in.

```
local: wiping 4/4
0: Process exited with status 1: zsh:1: no matches found: /home/arjun/local/1/certs*

1: Process exited with status 1: zsh:1: no matches found: /home/arjun/local/2/certs*

2: Process exited with status 1: zsh:1: no matches found: /home/arjun/local/3/certs*

3: Process exited with status 1: zsh:1: no matches found: /home/arjun/local/4/certs*
```

`roachprod destroy` gives the same error message.

**Comment by petermattis** [comment]
Doesn't happen for me. Perhaps there is something different with zsh (I use bash).

**Comment by benesch** [comment]
We should probably always use Bash.

**Comment by bobvawter** [comment]
@arjunravinarayan Just curious, but will using an ssh forced command do the job?

In your `~/.ssh/authorized_keys`, if you prefix your local identity's entry like so, does the command work?

```
command="/bin/bash -c '$SSH_ORIGINAL_COMMAND'" ssh-rsa YOUR-KEY-DATA
```

Otherwise, we can take every use of `ssh.Session.CombinedOutput()` and related functions to wrap the invocation in a `/bin-bash -c` setup.

Also, how many Roachers use shells other than bash?  Thoughts?

**Comment by jordanlewis** [comment]
I use `zsh` as well. The problem is a difference in expansion behaviour between the two shells. 

```
			cmd = fmt.Sprintf(`rm -fr ${HOME}/local/%d/{certs*,data,logs} ;`, c.Nodes[i])
```

Could we just change this line to `rm -fr ${HOME}/local/%d/*` instead?

**Comment by benesch** [comment]
IIRC there might be things we don't want to delete in `~/local/x/`, like a cockroach binary.

**Comment by petermattis** [comment]
> IIRC there might be things we don't want to delete in ~/local/x/, like a cockroach binary.

That's correct. We could certainly manually perform the brace expansion.

**Comment by bobvawter** [comment]
I'll tweak the code to expand the braces.
