### ISSUE TITLE
Allow "tagging" of processes created by roachprod

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/roachprod#123]
Currently `roachprod` tags processes it creates with `ROACHPROD=<node>` environment variables. This allows `roachprod` to find the status of and kill processes that it started. We've discovered the need to be able to group the remote processes. A concrete proposal for how to do so is to add a `--tag` flag to be used by `start`, `ssh`, `run`, `sql`, `stop`, etc, that would extend the environment variable to have the form `ROACHPROD=<node>/<tag>`.

**Comment by bdarnell** [comment]
Is it time to consider an actual process manager (e.g. supervisord or systemd) running on the machine instead of this environment variable hack?

**Comment by petermattis** [comment]
> Is it time to consider an actual process manager (e.g. supervisord or systemd) running on the machine instead of this environment variable hack?

Do you have thoughts on what using `supervisord` or `systemd` would give us? For the most part, I find `supervisord` to be an unnecessary level of indirection. I don't have any significant experience with `systemd`.

**Comment by bdarnell** [comment]
In this context, the main thing it gives you is the ability to name your processes so you can refer to them with stable identifiers (with wildcards) instead of their pids.

**Comment by benesch** [comment]
In my experience neither supervisor nor systemd is designed to handle changing flags on the fly. `roachprod start` allows you to specify different flags on every invocation. I think we'd be stuck rewriting the service definition on every call to `roachprod start`, no? And `roachprod ssh` is creating arbitrary processes that might not match a known service.

I think I agree with Peter that a process manager won't give us much here. Especially considering we don't actually want the restart-on-fail behavior.
