### ISSUE TITLE
Make roachprod --local work without ssh

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/roachprod#128]
I tried to start running some of our roachtests on every PR using --local, but the builder image doesn't have ssh (and probably shouldn't). It's also an extra step for each dev to set up passwordless ssh to localhost before they can use --local

**Comment by justinj** [comment]
This would be nice for when my login shell isn't posix compliant (I know, I know):
```
$ roachprod destroy local
local: stopping 2/2
0: Process exited with status 127: Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
fish:   awk '/ROACHPROD=(1)[ \/]/ { print $1 }' | xargs kill -9 || true;
                                                                 ^
```

**Comment by tschottdorf** [comment]
@justinj can't you work around that? Set up a user, put the keys into your actual user's `~/.ssh`, give that user `/bin/bash` as a login shell.

**Comment by bdarnell** [comment]
`roachprod` shouldn't be relying on the user's login shell. it should wrap everything in `sh -c` itself when needed.

**Comment by petermattis** [comment]
I took a look at what it would take to fix this issue. It isn't particularly difficult, just a bunch of manual lifting. @benesch I'm going to take this off your plate and try to get to it soon.

**Comment by benesch** [comment]
Huh. I thought I saw a solution that didn't involve much manual lifting at all. Specifically by extracting a `Execer` interface that both an SSH connection and `exec.Command` could fulfill.

**Comment by petermattis** [comment]
@benesch I looked at that, but it is more than just extracting an interface as we access `Session.{Stdout,Stderr}` fields and might have a few other bits that don't fit into a shared interface. I think there also needs to be special handling for `Get` (there already is for `Put`) to perform local file copies. I don't think it will be too hard, just need to find a few hours to do the work.
