### ISSUE TITLE
Unify `roachprod run` and `roachprod ssh`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/roachprod#138]
The `run` and `ssh` subcommands are almost but not quite identical: `ssh` can be interactive, but only runs against one node, while `run` is never interactive but supports parallel execution across multiple nodes. There are other subtle differences, like the fact that `ssh` runs the `expander` on its arguments while `run` does not. We should combine these into one command that supports multiple nodes in non-interactive mode (so we only have one interpretation of non-interactive commands) while also supporting interactive use on a single node.

**Comment by petermattis** [comment]
I agree this is confusing. I think I have a TODO about this some where.
