### ISSUE TITLE
Support compression in `roachprod put`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/roachprod#142]
If `roachprod put` shelled out to scp (or rsync) instead of using the go ssh implementation, we could compress the files we copy over to speed things up a bit. (Something like google's old `treedist` would be even better, but that's a refactor for another day)

**Comment by benesch** [comment]
The tradeoff here is that we'd have to give up the per-node progress bars. Unless you know of some way to programmatically extract progress information from scp/rsync.

**Comment by tschottdorf** [comment]
On a related note, I was thinking that it would make sense to be able to move files from one node to another. For example, starting a 10 node cluster means uploading the binary ten times, which is quite a drag. Instead, you could `c.Put` it on the first node and then `c.Copy` it to another one.

Another option is that when you don't care that the binary is locally built, the remote could use `binfetcher` to grab it from our buckets. But making that tool right is an interesting problem. I suppose we could pass `--cockroach binfetcher://LATEST` or something like that to enable this use case.

**Comment by benesch** [comment]
>
> Hmm, yeah. Why are we building up all this functionality ourselves from
> scratch again instead of using ansible/salt/puppet/etc?


I think @petermattis is scarred by terraform.

**Comment by petermattis** [comment]
> I think @petermattis is scarred by terraform.

Aren't we all?
