### ISSUE TITLE
`stop` should wait for processes to exit

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/roachprod#219]
`stop` should wait for the processes to exit in order to prevent the caller from running into problems with restarting cockroach too quickly before the previous cockroach has released OS file locks. Something along the lines of:

```
while $(kill -0 $PID 2>/dev/null); do
  sleep 1
done
```

**Comment by benesch** [comment]
This is somewhat complicated by the fact that `roachprod stop` supports sending arbitrary signals, but I guess we don't really care about supporting `roachprod stop --signal SIGHUP`.

**Comment by petermattis** [comment]
We could also condition that waiting on the signal being sent (i.e. only wait for a small set of whitelisted signals). Or add a `--wait` flag (default false) so that you can do `roachprod stop --signal SIGHUP --wait false`.

**Comment by benesch** [comment]
I like the wait flag idea. With the exception of SIGKILL you can’t be
assured that the process will exit in any kind of timely fashion. And if
I’m not mistaken `roachprod stop` is also used to stop things that are not
cockroach?

**Comment by petermattis** [comment]
Yes `stop` sends a signal to all processes with the `ROACHPROD=%d` env var.

**Comment by petermattis** [comment]
I'm taking a crack at this. Rather than `kill -0`, I think we can loop looking for processes with the `ROACHPROD=%d` env until there are none left.
