### ISSUE TITLE
crl tools don't work on new roachprod cluster

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/roachprod#39]
I created a cluster with `roachprod create alex-chaos -l 80h -n 6`.

`crl-stage-binaries` and `crl-ssh` just hang forever:

```console
$ crl-stage-binaries alex-chaos all scripts
1: # user@host          locality
ssh: connect to host locality port 22: Operation timed out
lost connection
```

```console
$ crl-ssh alex-chaos 1
1: # user@host          locality
ssh: connect to host # port 22: Operation timed out
```

Whereas SSH'ing directly to the VM works fine:

```console
$ gcloud compute ssh alex-chaos-0001 --project=cockroach-ephemeral --zone=us-east1-b
Warning: Permanently added 'compute.7394771536510255440' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.10.0-35-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Tue Jan 30 18:59:10 2018 from 173.194.90.32
alex@alex-chaos-0001:~$
```

I've already run `ssh-add ~/.ssh/google_compute_engine`, so that's not the problem.

What's changed here?

I used roachprod at commit 8de6bcfd60a00ec069a1be2fe3e43451aac165cf, if it makes a difference.

@petermattis

**Comment by petermattis** [comment]
Both `crl-ssh` and `roachprod ssh` (new!!!) work for me. I just tested on a brand new `roachprod` created cluster. I'm not sure what you're doing differently.

**Comment by a-robinson** [comment]
It was the format of the roachprod hosts file -- it didn't like the `# user@host          locality` first line or the locality attributes at the end of each line. I just removed that info, but it looks like pulling in https://github.com/cockroachlabs/production/commit/8089268cb85029984d8765796c2c42c7de220db4 would have fixed it as well.
