### ISSUE TITLE
`roachprod stop` kills too much

### ISSUE THREAD

**Issue by benesch** [cockroachdb/roachprod#60]
If running a local cluster, `roachprod stop cockroach` will terminate a running Cockroach build, not just the nodes in the cluster. Perhaps `killall` would work better than `pkill`?

**Comment by petermattis** [comment]
I thought `pkill` as the equivalent of `killall`. Is it not?

**Comment by benesch** [comment]
pkill matches against the process name and its entire argument list; killall only considers the process name. https://unix.stackexchange.com/a/91540/212232

**Comment by benesch** [comment]
Hmm, wait, maybe that's not true. Perhaps there's something fishier at play.

**Comment by petermattis** [comment]
Did you ever figure out what is going on here?

**Comment by tschottdorf** [comment]
This is pretty annoying (it just killed a long-running fixture generation halfway through). Taking a look.

**Comment by benesch** [comment]
Were you running `cockroach` as part of that fixture generation, Tobi?

**Comment by tschottdorf** [comment]
@benesch I'm not sure what I actually did, but now I think it must've been funky. I was running something like `workload fixtures store tpcc --warehouses 400` but that would've connected to my roachtest cluster at `:26257` and so the `lsof -i` rightly killed it. Another problem I had is that if the test runner itself connects to one of the nodes, it too will be in the lsof, and so it `kill -9`s itself. That usually means that when there's a problem in the test, all you get is a SIGKILL and you don't know what happened, which is pretty terrible. I'm not sure how to address that while sticking to the `lsof` approach -- filtering by LISTEN would work, but requires awkward grep yoga.

**Comment by petermattis** [comment]
@tschottdorf `roachprod status` uses an `lsof` command to find the process listening on the cockroach port: `lsof -i :%d -i :%d -sTCP:LISTEN`.

**Comment by tschottdorf** [comment]
`Status` does, but not `Stop` or `Wipe` (which are the ones I looked at). I wasn't aware of `-s`, looks like all that's needed is some copy&paste then.

**Comment by petermattis** [comment]
@tschottdorf Right, `stop` and `wipe` use a different `lsof` command. The intention was that `stop` should stop everything started by `roachprod` including load generators.

**Comment by tschottdorf** [comment]
These are still called in `roachtest -local`, so we should probably adapt them and find a way to explicitly target the load generators (in an ideal world it would only target the "own" load generators, but I guess that's too much of a hassle). It was confusing when `Wipe()` killed `roachtest` itself. That'll happen to the next person as well.

**Comment by petermattis** [comment]
Brainstorming: we could start the load generators (and everything started by `roachprod`) with an environment variable. That is, every command started by `roachprod would be started as `ROACHPROD=true <command>`. I think we could use this on linux to find the processes with that env variable set (at least from a smaller list of processes). Not sure how to use that on Mac OS X, but perhaps this will spur a better idea from someone else.

**Comment by tschottdorf** [comment]
Looks like this can be done on OSX as well: https://apple.stackexchange.com/questions/140327/how-can-i-inspect-the-environment-variables-of-a-running-process

**Comment by petermattis** [comment]
`ps eww`! Feels like a joke.

@tschottdorf Are you planning to work on this? My week is busy until Friday, so if you're in a rush...

**Comment by petermattis** [comment]
Brainstorm 2: can we start the processes under `roachprod` in such a way that they have a particular file descriptor opened to a particular file? If yes, then we could probably use `lsof` to find processes with that file open. I think this might be possible after perusing http://tldp.org/LDP/abs/html/io-redirection.html but I'm not sure. What I'd like to be able to do is to "tag" every process started by `roachprod` such that we can find it with `lsof` later.
