### ISSUE TITLE
add a secure option

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/roachprod#85]
It would be nice if we could create a roachprod cluster that was set up securely - with generated certificates so that internode communication was secure, as well as securing the ports so that no SQL client/admin UI connection could be made without proper certificates/ssh tunneling. 

If we have real data that we want to use in reproducing performance/stability issues, we are currently unable to use roachprod to do so.

**Comment by petermattis** [comment]
`roachprod start --secure` exists, though you have to provide the `certs` dir on each node. Automatically creating the `certs` dir should be possible.
