### ISSUE TITLE
Add option to stop vms instead of deleting

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/roachprod#89]
It's very inconvenient to recreate a roachprod cluster from scratch if it took a long time to get into a certain state. For example, it takes a long time to import the TPCC dataset.

I've been running `roachprod extend` a lot to prevent my cluster from getting deleted at night and over the weekend. However, I might not be using the cluster that whole time, which is a waste of money.

Can we add an option to merely stop the VMs when they expire? Similar to what the gceworker does.

**Comment by a-robinson** [comment]
I agree this would be nice, but note that GCE VMs with local SSDs attached can't be stopped, so it'd only be possible on clusters not using local SSD.

**Comment by jordanlewis** [comment]
Ah, didn't realize. Well, just going to close this then.
