### ISSUE TITLE
`roachprod local` ssh failure requires a better error message

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/roachprod#98]
There was a cryptic error message saying 'failed' and nothing more. I needed to install openssh-server, and create a new passphrase-less rsa keypair and add it to my `authorized_keys` to get it to work.

**Comment by benesch** [comment]
Instead of creating a new passphrase-less SSH key, it's usually possible to add your key to the agent instead. (`ssh-add ~/.ssh/id_rsa`)

I agree it's real confusing, though.

**Comment by arjunravinarayan** [comment]
the error was more to motivate a better error message when local ssh fails. i'll change the title.

**Comment by petermattis** [comment]
@bobvawter Can you see about making this error a bit more pleasant? It seems to strike every new user of `roachprod`.
